Various improvements

diff --git a/hooks/install b/hooks/install
--- a/hooks/install
+++ b/hooks/install
@@ -6,7 +6,7 @@ source inc/common
 
 add-apt-repository -y ppa:natecarlson/maven3
 apt-get update
-apt-get install -y maven3
+apt-get install -y maven3 gnupg
 juju-log "Maven 3 installed"
 
 if [ ! -d "$BASE_SRC/$PROJECT_NAME" ]; then
@@ -39,19 +39,48 @@ else
     if [ "$JEE_CONTAINER" == "jboss" ]; then
 	juju-log "Go for JBoss"
     else
-	TOMCAT_VERSION="7.0.50"
+	TOMCAT_VERSION="7.0.52"
 	juju-log "Go for Tomcat $TOMCAT_VERSION under $TOMCAT_HOME"
 	
 	if [ ! -d $TOMCAT_HOME ]; then
 	    juju-log "Downloading Tomcat $TOMCAT_VERSION..."
 
 	    cd /tmp
-	    wget_output=$(wget -qN http://archive.apache.org/dist/tomcat/tomcat-7/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz)
+	    wget_output=$(wget -qN https://archive.apache.org/dist/tomcat/tomcat-7/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz)
 	    if [ $? -ne 0 ]; then
 		juju-log "Cannot download Tomcat $TOMCAT_VERSION: aborting"
 		exit $?
 	    fi
+	    wget_output=$(wget -qN https://archive.apache.org/dist/tomcat/tomcat-7/KEYS)
+	    if [ $? -ne 0 ]; then
+		juju-log "Cannot download Tomcat KEYS: aborting"
+		exit $?
+	    fi
+	    wget_output=$(wget -qN https://archive.apache.org/dist/tomcat/tomcat-7/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz.asc)
+	    if [ $? -ne 0 ]; then
+		juju-log "Cannot download Tomcat $TOMCAT_VERSION ASC: aborting"
+		exit $?
+	    fi
+	    wget_output=$(wget -qN https://archive.apache.org/dist/tomcat/tomcat-7/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz.md5)
+	    if [ $? -ne 0 ]; then
+		juju-log "Cannot download Tomcat $TOMCAT_VERSION MD5: aborting"
+		exit $?
+	    fi
 
+	    # Verify the downloaded archive
+	    md5sum --status -c apache-tomcat-$TOMCAT_VERSION.tar.gz.md5
+	    if [ $? -ne 0 ]; then
+		juju-log "$TOMCAT_VERSION MD5 verification failed: aborting"
+		exit $?
+	    fi
+	    gpg_output=$(gpg --import KEYS)
+	    gpg_output=$(gpg --verify apache-tomcat-$TOMCAT_VERSION.tar.gz.asc)
+	    if [ $? -ne 0 ]; then
+		juju-log "$TOMCAT_VERSION ASC verification failed: aborting"
+		exit $?
+	    fi
+	    
+	    # Install Tomcat and perform basic configuration
 	    cd /opt
 	    tar xvzf /tmp/apache-tomcat-$TOMCAT_VERSION.tar.gz
 	    ln -s apache-tomcat-$TOMCAT_VERSION apache-tomcat
